name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0
        with:
          driver-opts: |
            image=moby/buildkit:v0.10.6
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false
      - name: Build and push Docker image no open telemetry version
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.no-otel
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/s-mishina/spring-boot-jmx-metrics-sample:no-otel_${{ github.sha }}
            ghcr.io/s-mishina/spring-boot-jmx-metrics-sample:no-otel-latest
      - name: Build and push Docker image open telemetry version
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.otel
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/s-mishina/spring-boot-jmx-metrics-sample:otel_${{ github.sha }}
            ghcr.io/s-mishina/spring-boot-jmx-metrics-sample:otel-latest
